# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-31 02:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_dates',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 2, 5, 56, 330000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 2, 5, 56, 330000, tzinfo=utc)),
        ),
    ]
