# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-31 02:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190730_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_dates',
        ),
        migrations.AddField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 2, 7, 45, 345000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 2, 7, 45, 345000, tzinfo=utc)),
        ),
    ]
